apiVersion: v1
kind: Pod
metadata:
  name: gpu-demo
spec:
  containers:
  - name: test
    image: dklabjan/keras-gpu
    command: ["sleep"]
    args: ["infinity"]
  nodeSelector:
    kubernetes.io/hostname: ptuj.iems.private
